
package services.aic11.infosys.tuwien.ac.at;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.Future;

import javax.xml.namespace.QName;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-13T03:19:26.438+01:00
 * Generated source version: 2.5.0
 * 
 */
public final class Shipping_ShippingPort_Client {

    private static final QName SERVICE_NAME = new QName("http://at.ac.tuwien.infosys.aic11.services", "ShippingService");

    private Shipping_ShippingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShippingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShippingService ss = new ShippingService(wsdlURL, SERVICE_NAME);
        Shipping port = ss.getShippingPort();  
        
        {
        System.out.println("Invoking shipContractAsync...");
        dto.aic11.infosys.tuwien.ac.at.Offer _shipContractAsync_offer = null;
        Response<services.aic11.infosys.tuwien.ac.at.ShipContractResponse> _shipContractAsync__return = port.shipContractAsync(_shipContractAsync_offer);
        System.out.println("shipContractAsync.result=" + _shipContractAsync__return);


        }
        {
        System.out.println("Invoking shipContractAsync...");
        dto.aic11.infosys.tuwien.ac.at.Offer _shipContractAsync_offer = null;
        AsyncHandler<services.aic11.infosys.tuwien.ac.at.ShipContractResponse> _shipContractAsync_asyncHandler = null;
        Future<?> _shipContractAsync__return = port.shipContractAsync(_shipContractAsync_offer, _shipContractAsync_asyncHandler);
        System.out.println("shipContractAsync.result=" + _shipContractAsync__return);


        }
        {
        System.out.println("Invoking shipContract...");
        dto.aic11.infosys.tuwien.ac.at.Offer _shipContract_offer = null;
        try {
            dto.aic11.infosys.tuwien.ac.at.Offer _shipContract__return = port.shipContract(_shipContract_offer);
            System.out.println("shipContract.result=" + _shipContract__return);

        } catch (ShippingException_Exception e) { 
            System.out.println("Expected exception: ShippingException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
