
package services.aic11.infosys.tuwien.ac.at;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-13T03:19:26.463+01:00
 * Generated source version: 2.5.0
 */

@SuppressWarnings("serial")
@WebFault(name = "ShippingException", targetNamespace = "at.ac.tuwien.infosys.aic11.services")
public class ShippingException_Exception extends Exception {
    
    private services.aic11.infosys.tuwien.ac.at.ShippingException shippingException;

    public ShippingException_Exception() {
        super();
    }
    
    public ShippingException_Exception(String message) {
        super(message);
    }
    
    public ShippingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ShippingException_Exception(String message, services.aic11.infosys.tuwien.ac.at.ShippingException shippingException) {
        super(message);
        this.shippingException = shippingException;
    }

    public ShippingException_Exception(String message, services.aic11.infosys.tuwien.ac.at.ShippingException shippingException, Throwable cause) {
        super(message, cause);
        this.shippingException = shippingException;
    }

    public services.aic11.infosys.tuwien.ac.at.ShippingException getFaultInfo() {
        return this.shippingException;
    }
}
