package services.aic11.infosys.tuwien.ac.at;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-13T03:19:26.471+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", name = "Shipping")
@XmlSeeAlso({ObjectFactory.class, dto.aic11.infosys.tuwien.ac.at.ObjectFactory.class})
public interface Shipping {

    @RequestWrapper(localName = "ship_contract", targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", className = "services.aic11.infosys.tuwien.ac.at.ShipContract")
    @ResponseWrapper(localName = "ship_contractResponse", targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", className = "services.aic11.infosys.tuwien.ac.at.ShipContractResponse")
    @WebMethod(operationName = "ship_contract")
    public Response<services.aic11.infosys.tuwien.ac.at.ShipContractResponse> shipContractAsync(
        @WebParam(name = "offer", targetNamespace = "")
        dto.aic11.infosys.tuwien.ac.at.Offer offer
    );

    @RequestWrapper(localName = "ship_contract", targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", className = "services.aic11.infosys.tuwien.ac.at.ShipContract")
    @ResponseWrapper(localName = "ship_contractResponse", targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", className = "services.aic11.infosys.tuwien.ac.at.ShipContractResponse")
    @WebMethod(operationName = "ship_contract")
    public Future<?> shipContractAsync(
        @WebParam(name = "offer", targetNamespace = "")
        dto.aic11.infosys.tuwien.ac.at.Offer offer,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<services.aic11.infosys.tuwien.ac.at.ShipContractResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ship_contract", targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", className = "services.aic11.infosys.tuwien.ac.at.ShipContract")
    @WebMethod(operationName = "ship_contract")
    @ResponseWrapper(localName = "ship_contractResponse", targetNamespace = "http://at.ac.tuwien.infosys.aic11.services", className = "services.aic11.infosys.tuwien.ac.at.ShipContractResponse")
    public dto.aic11.infosys.tuwien.ac.at.Offer shipContract(
        @WebParam(name = "offer", targetNamespace = "")
        dto.aic11.infosys.tuwien.ac.at.Offer offer
    ) throws ShippingException_Exception;
}
